- name: Create EC2
  hosts: [localhost]
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    application: djangoblue
    region: us-west-2
  
  tasks:
    - name: Collect EC2 info
      ec2_instance_info:
        instance_ids:
          - i-0979a2b756551685c
      with_register: ec2_instance
      
    - name: Add EC2 instance to host
      add_host:
        name: "{{ item.public_ip }}"
        groups: server
      with_items: "{{ ec2_instance.tagged_instances }}"

- name: Deploy EC2
  hosts: server
  remote_user: ubuntu
  become: yes 
  gather_facts: false

  tasks:
    - name: Install Docker
      apt:
        name: docker

    - name: Pull & Run Docker
      docker_container:
        name: django_container
        image: zhan430/traveblog:lastest
        pull: yes
        state: started

- name: Setup Route53
  hosts: [localhost]
  gather_facts: false

  tasks:
    - name: Add EC2 instance to ELB
      ec2_elb:
        state: present
        ec2_elbs: elb.name
        region: "{{ region }}"
        instance_id: "{{ item.id }}"
      with_items: "{{ ec2_instance.tagged_instances }}"

    - name: change route53
      route53:
        state: present
        zone: lazxy.com
        record: www.lazxy.com
        failover: PRIMARY
        type: CNAME
        ttl: 30
        identifier: blue
        private_zone: yes
        overwrite: yes
        value: "{{ application }}-load-balancer"
        wait: yes
        health_check: "f727fa34-2bbd-4288-b59f-7ca9f74c5f34"


